force-app/main/default/objects/Event_Plan__c/Event_Plan__c.object-meta.xml
<CustomObject>
    <description>Represents individual events planned by EventPro.</description>
    <label>Event Plan</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Event Plan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Plan__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>The date and time of the event.</description>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event_Plan__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <description>The name of the event</description>
    <label>Event Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/Event_Task__c.object-meta.xml
<CustomObject>
    <description>Represents tasks associated with event planning</description>
    <label>Event Task</label>
    <nameField>
        <displayFormat>ET-{0000}</displayFormat>
        <label>Event Task ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user assigned to complete the task.</description>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>The deadline for completing the task.</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/fields/Event_Plan__c.field-meta.xml
<CustomField>
    <fullName>Event_Plan__c</fullName>
    <description>The event plan associated with the event task.</description>
    <label>Event Plan</label>
    <referenceTo>Event_Plan__c</referenceTo>
    <relationshipLabel>Event Tasks</relationshipLabel>
    <relationshipName>Event_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Task__c/fields/Task_Name__c.field-meta.xml
<CustomField>
    <fullName>Task_Name__c</fullName>
    <description>The name of the task.</description>
    <label>Task Name</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventRunningSheetController.cls
/**
 * @description       : 
 * @author            : Ajshe Aktash
 * @group             : 
 * @last modified on  : 10-29-2023
 * @last modified by  : Ajshe Aktash
**/
public with sharing class EventRunningSheetController {
    @AuraEnabled(cacheable=true)
    public static Event_Plan__c getEventDetails(String recordId) {
        // Use SOQL query to retrieve event details, including Event Name and Event Date
        return [SELECT Name, Event_Date__c , Event_Name__c FROM Event_Plan__c WHERE Id = :recordId  LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Event_Task__c> getTasks(String recordId) {
        // Use SOQL query to retrieve task records, including Task Name, Due Date, and Assigned To
        return [SELECT Task_Name__c, Due_Date__c, Assigned_To__c FROM Event_Task__c WHERE Event_Plan__c = :recordId ORDER BY Due_Date__c];
    }
}